openapi: 3.0.3

info:
  title: cashezavr bill
  description: Информация о выплатах
  version: 1.0.0

servers:
  - url: 'wait.ru'

paths:
  /cashezavr/core/bill/getAll:
    get:
      tags:
        - bill
      description: Получение списка всех проведенных выплат
      operationId: getAllBills
      responses:
        200:
          description: Список выплат
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/BillDto"


  /cashezavr/core/bill/require:
    post:
      tags:
        - bill
      description: Запрос выплаты
      operationId: requireBill
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/BillRequireDto"
      responses:
        200:
          description: Успешно


components:
  schemas:
    BillDto:
      properties:
        created:
          type: string
          format: date-time
        sum:
          type: number
        status:
          type: string

    BillRequireDto:
      properties:
        sum:
          type: number