openapi: 3.0.3

info:
  title: cashezavr register
  description: Регистрация нового пользователя
  version: 1.0.0

servers:
  - url: 'wait.ru'

paths:
  /cashezavr/register:
    post:
      tags:
        - register
      description: Регистрация нового пользователя
      operationId: register
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/RegisterDto"
      responses:
        200:
          description: Успешно
        409:
          description: Такой пользователь уже существует

  /cashezavr/try:
    get:
      tags:
        - register
      description: Проверка успешности авторизации
      operationId: tryAuth
      responses:
        200:
          description: Успешно
        401:
          description: Иди авторизуйся


components:
  schemas:
    RegisterDto:
      properties:
        username:
          type: string
        password:
          type: string
        email:
          type: string
        phone:
          type: string

  
