apiVersion: v1
kind: PersistentVolume
metadata:
  name: cert-pv
  labels:
    type: local
    app: cert
spec:
  storageClassName: manual
  capacity:
    storage: 20M
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/data/cert"

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cert-pvc
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20M
