scrape_configs:
  - job_name: 'cashezavr-core monitor'
    scrape_interval: 10s
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['cashezavr-core.cashezavr']

  - job_name: 'cashezavr-outside monitor'
    scrape_interval: 10s
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['cashezavr-outside.cashezavr']

  - job_name: 'cashezavr-production monitor'
    scrape_interval: 10s
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'cashezavr-production.cashezavr' ]

  - job_name: 'grafana monitor'
    scrape_interval: 10s
    metrics_path: '/metrics'
    static_configs:
      - targets: ['cashezavr.monitoring']

  - job_name: 'kube-state-metrics'
    static_configs:
      - targets: [ 'kube-state-metrics.kube-metrics.svc.cluster.local:8080' ]