apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: proxy
  namespace: argocd
  labels:
    type: cluster
spec:
  destination:
    namespace: cluster
    server: https://kubernetes.default.svc
  project: cashezavr
  source:
    path: cashezavr-iac/kubernetes/cluster/proxy
    repoURL: git@github.com:umu-art/cashezavr.git
    targetRevision: master
  syncPolicy:
    automated:
      prune: true