apiVersion: apps/v1
kind: Deployment

metadata:
  name: cashezavr-outside
  namespace: cashezavr
  labels:
    app: cashezavr-outside

spec:
  replicas: 1

  selector:
    matchLabels:
      app: cashezavr-outside

  template:
    metadata:
      name: cashezavr-outside
      labels:
        app: cashezavr-outside

    spec:
      containers:
        - name: cashezavr-outside
          image: ghcr.io/umu-art/cashezavr-outside:master
          imagePullPolicy: Always

          env:
            - name: JAVA_OPTS
              value: >-
                -Dspring.config.location=file:/config/application.yml

            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: cashezavr-secrets
                  key: POSTGRES_DB

            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: cashezavr-secrets
                  key: POSTGRES_USER

            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: cashezavr-secrets
                  key: POSTGRES_PASSWORD

            - name: RABBIT_USER
              valueFrom:
                secretKeyRef:
                  name: cashezavr-secrets
                  key: RABBIT_USER

            - name: RABBIT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: cashezavr-secrets
                  key: RABBIT_PASSWORD

            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: cashezavr-secrets
                  key: REDIS_PASSWORD

          volumeMounts:
            - name: config
              mountPath: /config

          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 3002
            initialDelaySeconds: 40
            periodSeconds: 10
            failureThreshold: 15

          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 3002
            initialDelaySeconds: 40
            periodSeconds: 10
            failureThreshold: 15

          resources:
            requests:
              memory: "350Mi"
              cpu: "500m"
            limits:
              memory: "500Mi"
              cpu: "1000m"

      volumes:
        - name: config
          configMap:
            name: application-properties-outside

      imagePullSecrets:
        - name: github-container-registry

      restartPolicy: Always
      