openapi: 3.0.3

info:
  title: Cherry outside-auth
  description: Авторизация outside интеграции в ФНС, передача номера симки и смски
  version: 1.0.0

servers:
  - url: 'wait.ru'

paths:
  /cherry/outside/send-message:
    post:
      tags:
        - outside-auth
      description: Запрос на отправку сообщения
      requestBody:
        content:
          application/json:
            schema:
              description: Номер телефона
              title: phone
              type: string
      responses:
        200:
          description: OK

  /cherry/outside/code:
    post:
      tags:
        - outside-auth
      description: Отправка кода подтверждения
      requestBody:
        content:
          application/json:
            schema:
              description: Код
              title: code
              type: string
      responses:
        200:
          description: OK
