apiVersion: batch/v1
kind: CronJob
metadata:
  name: cashezavr-load-recovery
  namespace: cashezavr-utils
spec:
  schedule: "*/10 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: cashezavr-load-recovery
              image: ghcr.io/umu-art/cashezavr-load-recovery:master
              imagePullPolicy: Always

          imagePullSecrets:
            - name: github-container-registry

          restartPolicy: Never