apiVersion: batch/v1
kind: CronJob
metadata:
  name: cashezavr-load-recovery
  namespace: cashezavr-utils
spec:
  schedule: "*/10 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: cashezavr-load-recovery
              image: ghcr.io/umu-art/cashezavr-load-recovery:master
              imagePullPolicy: Always

          env:
            - name: RABBIT_USER
              valueFrom:
                secretKeyRef:
                  name: cashezavr-secrets
                  key: RABBIT_USER

            - name: RABBIT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: cashezavr-secrets
                  key: RABBIT_PASSWORD

          imagePullSecrets:
            - name: github-container-registry

          restartPolicy: Never