apiVersion: v1
kind: Service
metadata:
  name: proxy
  namespace: cluster
spec:
  selector:
    app: proxy
  ports:
    - name: http
      port: 80
      protocol: TCP

    - name: grpc
      port: 5445
      protocol: TCP

  type: LoadBalancer
