spring:
  application:
    name: cashezavr-core

  datasource:
    url: jdbc:postgresql://localhost:5432/cherry_dev
    username: cherry
    password: cherry
  flyway:
    baseline-on-migrate: true
    baseline-version: 0.0.1

  jpa:
    hibernate:
      ddl-auto: update  # TODO: migrations
    open-in-view: false

cherry:
  receipts:
    poll:
      maxTime: 5000
      waitTime: 100

server:
  port: 3001
  error:
    include-exception: true
    include-message: always
    include-binding-errors: always

rabbit:
  host: localhost
  login: rmuser
  password: rmpassword

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,metrics
  endpoint:
    health:
      show-details: always
  prometheus:
    metrics:
      export:
        enabled: true
  tracing:
    sampling:
      probability: 1.0
  metrics:
    tags:
      application: ${spring.application.name}
    distribution:
      percentiles-histogram:
        http:
          server:
            requests: true
  zipkin:
    tracing:
      endpoint: http://tempo:9411/api/v2/spans

logging:
  level:
    root: info
    ru.kazenin: trace
    org.hibernate.SQL: trace

