apiVersion: v1
kind: Service
metadata:
  name: cashezavr-production
spec:
  selector:
    app: cashezavr-production
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3003
  type: ClusterIP
