apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbit
  namespace: cherry
  labels:
    app: rabbit
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabbit
  template:
    metadata:
      name: rabbit
      labels:
        app: rabbit
    spec:
      containers:
        - name: rabbit
          image: dockerhub.timeweb.cloud/rabbitmq:3-management
          imagePullPolicy: Always
          env:
            - name: RABBITMQ_DEFAULT_USER
              value: rmuser
            - name: RABBITMQ_DEFAULT_PASS
              value: rmpassword
            - name: RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS
              value: -rabbit disk_free_limit 2147483648

          resources:
            requests:
              memory: "350Mi"
              cpu: "100m"
            limits:
              memory: "500Mi"
              cpu: "500m"

      restartPolicy: Always
      