apiVersion: v1
kind: Service
metadata:
  name: rabbit
  namespace: cherry
spec:
  selector:
    app: rabbit
  ports:
    - protocol: TCP
      port: 15672
      targetPort: 15672
    - protocol: TCP
      port: 5672
      targetPort: 5672
  type: NodePort
