{
 "title": "DB",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Список товаров",
   "type": "table",
   "gridPos": { "h": 22, "w": 13, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT name, SUM(count) FROM receipt_item GROUP BY name ORDER BY SUM(count) DESC "
    }
   ]
  },
  {
   "title": "Количество пользователей",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 13, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(uuid) FROM client "
    }
   ]
  },
  {
   "title": "Количество загруженных чеков",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(uuid) FROM receipt "
    }
   ]
  },
  {
   "title": "Состояние выгрузки чеков из ФНС",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 11, "x": 13, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(uuid) AS \"Не выгруженно из за ошибки\" FROM receipt WHERE (date IS NULL AND load_lock = true) "
    },
    {
     "rawSql": "SELECT COUNT(uuid) AS \"Выгруженно успешно\" FROM receipt WHERE date IS NOT NULL "
    },
    {
     "rawSql": "SELECT COUNT(uuid) AS \"Ожидает выгрузки\" FROM receipt WHERE (date IS NULL AND load_lock = false) "
    }
   ]
  }
 ]
}