apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
  namespace: cherry
  labels:
    app: grafana
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      name: grafana
      labels:
        app: grafana
    spec:
      containers:
        - name: grafana
          image: ghcr.io/umu-art/grafana:master
          imagePullPolicy: Always

          volumeMounts:
            - mountPath: /var/lib/grafana
              name: grafana-storage

      volumes:
        - name: grafana-storage
          persistentVolumeClaim:
            claimName: grafana-pvc

      imagePullSecrets:
        - name: github-container-registry

      restartPolicy: Always
      