apiVersion: apps/v1
kind: Deployment

metadata:
  name: cherry-production
  namespace: cherry
  labels:
    app: cherry-production

spec:
  replicas: 1

  selector:
    matchLabels:
      app: cherry-production

  template:
    metadata:
      name: cherry-production
      labels:
        app: cherry-production

    spec:
      containers:
        - name: cherry-production
          image: ghcr.io/umu-art/cherry-production:master
          imagePullPolicy: Always

          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 3001
            initialDelaySeconds: 40
            periodSeconds: 10
            failureThreshold: 8

          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 3001
            initialDelaySeconds: 40
            periodSeconds: 10
            failureThreshold: 8

          resources:
            requests:
              memory: "350Mi"
              cpu: "500m"
            limits:
              memory: "500Mi"
              cpu: "1000m"

      imagePullSecrets:
        - name: github-container-registry

      restartPolicy: Always
