apiVersion: apps/v1
kind: Deployment
metadata:
  name: vpn
  namespace: cluster
  labels:
    app: vpn
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vpn
  template:
    metadata:
      name: vpn
      labels:
        app: vpn
    spec:
      containers:
        - name: vpn
          image: ghcr.io/linuxserver/wireguard
          imagePullPolicy: Always

          securityContext:
            privileged: true
            capabilities:
              add: ["NET_ADMIN", "SYS_MODULE"]

          env:
            - name: TZ
              value: "Europe/Moscow"
            - name: SERVERURL
              value: "147.45.107.30"
            - name: SERVERPORT
              value: "30303"
            - name: PEERS
              value: "3"
            - name: PEERDNS
              value: "10.96.0.10"
            - name: INTERNAL_SUBNET
              value: "10.13.13.0"
            - name: ALLOWEDIPS
              value: "0.0.0.0/0"

          volumeMounts:
            - mountPath: /config/
              name: vpn-config

      volumes:
        - name: vpn-config
          persistentVolumeClaim:
            claimName: vpn-config-pvc

      restartPolicy: Always
      