apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: cherry
  labels:
    app: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      name: postgres
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: dockerhub.timeweb.cloud/postgres:latest
          imagePullPolicy: Always
          env:
            - name: POSTGRES_DB
              value: cherry_dev
            - name: POSTGRES_USER
              value: cherry
            - name: POSTGRES_PASSWORD
              value: cherry
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: db-storage

          resources:
            requests:
              memory: "350Mi"
              cpu: "100m"
            limits:
              memory: "500Mi"
              cpu: "500m"

      volumes:
        - name: db-storage
          persistentVolumeClaim:
            claimName: postgres-pvc

      restartPolicy: Always