apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: cherry
  labels:
    app: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      name: postgres
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: dockerhub.timeweb.cloud/bitnami/postgresql:latest
          imagePullPolicy: Always
          env:
            - name: POSTGRES_DB
              value: cherry_dev
            - name: POSTGRES_USER
              value: cherry
            - name: POSTGRES_PASSWORD
              value: cherry
      restartPolicy: Always
      