spring:
  application:
    name: cherry-production

  datasource:
    url: jdbc:postgresql://postgres:5432/cherry_dev
    username: cherry
    password: cherry

  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false

server:
  port: 3003
  error:
    include-exception: true
    include-message: always
    include-binding-errors: always

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,metrics
  endpoint:
    health:
      probes:
        enabled: true
      show-details: always
  health:
    livenessstate:
      enabled: true
  prometheus:
    metrics:
      export:
        enabled: true
  tracing:
    sampling:
      probability: 1.0
  metrics:
    tags:
      application: ${spring.application.name}
    distribution:
      percentiles-histogram:
        http:
          server:
            requests: true
  zipkin:
    tracing:
      endpoint: http://tempo.monitoring:9411/api/v2/spans

logging:
  level:
    root: info
    ru.kazenin: trace

