version: "3.9"

name: cherry_iac

services:

  redis:
    image: "redis:alpine"
    command: redis-server --requirepass cherry
    ports:
      - "6379:6379"
    environment:
      - REDIS_REPLICATION_MODE=master

  postgres:
    image: postgres:latest
    hostname: postgres
    environment:
      POSTGRES_DB: "cherry_dev"
      POSTGRES_USER: "cherry"
      POSTGRES_PASSWORD: "cherry"
    ports:
      - "5432:5432"

  rabbitmq:
    image: rabbitmq:3-management
    restart: always
    hostname: rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=rmuser
      - RABBITMQ_DEFAULT_PASS=rmpassword
      - RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS=-rabbit disk_free_limit 2147483648
    ports:
      - "15672:15672"
      - "5672:5672"