name: Deploy

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
    
env:
  REGISTRY: ghcr.io
  
jobs:
  build:
    runs-on: ubuntu-latest
    
    permissions:
      contents: read
      packages: write
      attestations: write

    steps:
    - name: Checkout
      uses: actions/checkout@v4
    
    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'liberica'
        cache: maven

    - name: Build api
      run: (cd cherry-iac/openapi; chmod 777 ./build-core-api.sh;  ./build-core-api.sh)
        
    - name: Build with Maven
      run: mvn -B package --file pom.xml
      
    - name: Log in to the Container registry
      uses: docker/login-action@v3.1.0
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@v5.5.1
      with:
        images: ${{ env.REGISTRY }}/${{ github.actor }}/cherry-core
      
    - name: Build and push Docker image
      id: push
      uses: docker/build-push-action@v5.3.0
      with:
        context: ./cherry-core
        file: ./cherry-core/Dockerfile
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
